title: ANDA Lab
baseurl: /site
url: https://anda-researchers.github.io
email: hpnq.work@outlook.com

base_path: /site

# Build settings
theme: minima
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
