title: ANDA Lab
description: >-
  The Advanced Network Design and Analysis (ANDA) Lab at Soongsil University focuses on cutting-edge research in Autonomous Vehicles, Machine Learning, Networking, Edge and Cloud Computing, and Sensor Networks. Join us in shaping the future of network technologies.
baseurl: /site/
url: https://anda-researchers.github.io

base_path: /site/

# Build settings
theme: minima
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
